/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/rightcave.ts" />
/// <reference path="../scenes/leftcave.ts" />
/// <reference path="../scenes/intro.ts" />
/// <reference path="../scenes/leftcave2.ts" />
/// <reference path="../scenes/rightcave2.ts" />
///<reference path="../scenes/scene13.ts" />
///<reference path="../scenes/scene14.ts" />
///<reference path="../scenes/scene9.ts" />
///<reference path="../scenes/scene5.ts" /> 
//# sourceMappingURL=_reference.js.map